### ISSUE TITLE
Add Message

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-9/chatty-stark#14]
## User Story
As a user, I should be able to add messages by clicking enter.

## AC
**Given** A user navigates to your page
**Then** they type in the input field
**And** when they hit enter a new message should be created
**And** the message should show up in the new chat window

## Dev Notes
* create a function called `addNewMessage`
  - `addNewMessage` will grab the value of the input field with the id=`new-message` and push to the `messages` array as an object.
  - Each new message being push to the `messages` object array will have a unique id. This can be implemented by a counter.
 - `printToDom` function should be called inside the `addNewMessage` function. This will loop over the `messages` array to reprint all of the messages to the div with an id of `messages-div`.
* `addNewMessage` function should clear the input field with the id=`new-message` after message has been added.

* Write a `keyup` event listener, this will call the `addNewMessage` function. 
  - See below for a MDN link on how to use `keyup` event.

**Comment by silvestreluna** [comment]
MDN KEYUP: 
https://developer.mozilla.org/en-US/docs/Web/API/Document/keyup_event
