### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-9/chatty-stark#2]
## User Story
As a user, when I navigate to your site, I should see a navbar.

## AC
**Given** A user navigates to your page
**Then** they should see a navbar
**And** it should have an application logo
**And** it should have an input field
**And** it should have a clear button
**And** it should remain at the top of the screen if the page scrolls

## Dev Notes
bootstrap navbar
logo and title of app in the far left corner
menu in the far right corner
** menu expands to show 'Settings'
** Clicking 'Settings' shows a modal with options for 'Accessibility'
** Accessibility modal has options for Larger Text and Increase Contrast (Dark Mode)

**Comment by samueltrejo** [comment]
![image](https://user-images.githubusercontent.com/47835231/56852283-d8276680-68de-11e9-8f58-d9bed24cda7d.png)

**Comment by samueltrejo** [comment]
navbar wireframe

![image](https://user-images.githubusercontent.com/47835231/56852374-72d47500-68e0-11e9-9e8b-8a7b3d6317e1.png)

**Comment by samueltrejo** [comment]
full app wireframe
*stretch goal is to alternate sides of messages depending on if you sent message or not

![image](https://user-images.githubusercontent.com/47835231/56852490-d01cf600-68e1-11e9-96d9-a5532e6e47b9.png)

**Comment by jeressia** [comment]
Link to NavBar (https://getbootstrap.com/docs/4.0/components/navbar/):

```
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Features</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown link
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
    </ul>
  </div>
</nav>
```

**Comment by samueltrejo** [comment]
full app wireframe

![image](https://user-images.githubusercontent.com/47835231/56853495-648d5580-68ee-11e9-9e3b-053a2df4d2d2.png)

**Comment by silvestreluna** [comment]
👍
