### ISSUE TITLE
Seed Data

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-9/chatty-stark#4]
## User Story
As a developer, in order to not have to wait, I would like some seed data

## AC
**Given** A developer navigated to your repo
**Then** they should see a file called `db/messages.json`
**And** this file should have seed data for 5 messages

## Dev Notes
* Create a `db` folder at the root all files
* Create a `db/chatty.json`
  - Inside `chatty.json`, use the below seed data.

**Comment by silvestreluna** [comment]
``` json
{
"messages": [{
    "id": 1,
    "imageUrl": "www.photolink.com",
    "userName": "Jeresia W",
    "msg": "Hello Test"
    },
    {
    "id": 2,
    "imageUrl": "www.photolink.com",
    "userName": "Sam T",
    "msg": "Hello Test"
  },
  {
    "id": 3,
    "imageUrl": "www.photolink.com",
    "userName": "Lwam T",
    "msg": "Hello Test"
  },
  {
    "id": 4,
    "imageUrl": "www.photolink.com",
    "userName": "Silvestre L",
    "msg": "Hello Test"
  }]
}

```

**Comment by silvestreluna** [comment]
Verified valid Json
